In [7]:

def myfun(a,b,c):
    mul=a*b*c
    return  mul

a=int(input(">"))
b=int(input(">"))
c=int(input(">"))    
print(myfun(a,b,c))

>2
>3
>1
6


In [8]:
def my(x):
    re=1
    x=str(x)
    for d in x:
        re *=x

In [14]:
import numpy as np
sam=[1,23,24]
print(type(sam))
sam=np.array(sam)
print(type(sam))
print(np.arange(0,11,2)) #0 and 10 is the range and 2 is difference

<class 'list'>
<class 'numpy.ndarray'>
[ 0  2  4  6  8 10]


In [22]:
np.random.seed(0) # ramdom no. wll nt change if we use seed 
a=np.random.randint(0,10,(3,3))# (3,3) is matrix  of 3*3  i.e 3 row & 3 col
a

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [23]:
np.random.seed(0)
a=np.random.randint(0,10,(3,3))# (3,3) is matrix  of 3*3  i.e 3 row & 3 col
a[2,2] # value of 2th row and 2th col

2

In [37]:
a[1:2]# slice operation

array([[3, 7, 9]])

In [40]:
a[1:,1:] # a[r,c] it wll give 1th row till end and 1th col till end of it

array([[7, 9],
       [5, 2]])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [50]:
np.ones((8,8))  np.zeros((8,8))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
users=input("Enter the number of users"))
print("Enter the user salary")